[build]
    command = "npm run build"
    publish = ".svelte-kit/build/"
    
[build.environment]
  NPM_FLAGS = "--version" # this prevents npm install from happening

[functions]
  node_bundler = "esbuild"